feat: Add SUB_SPECIALTY curricula to validator
Health-Education-England/tis-trainee-reference pull request #106
Opened 2021-07-26 13:57 UTC by Marcellofabbri

Validator now checks curricula are of curriculumSubType "SUB_SPECIALTY" as well as "MEDICAL_CURRICULUM"

**TIS21-1674**: add list of subspecialties to the Form R Part A Declarations Section

2021-07-26 15:01 UTC, JosephKelly requested changes
There's a change that probably merits bumping the version number up too

2021-07-26 15:01 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/trainee/reference/dto/validator/CurriculumValidatorTest.java
> +      "CURRENT,SUB_SPECIALTY, true",
For the sake of completeness (branch coverage), we should add the other test cases `"INACTIVE,SUB_SPECIALTY,false",...`.

2021-07-27 11:59 UTC, Marcellofabbri commented
Right, I've experimented a bit and found out what should happen if we retrigger the synchronization of the Curriculum table with the existing changes in tis-trainee-reference.

It looks like any new Curriculum being saved in the reference collection will indeed have the `curriculumSubType` attribute from now on. But as it is, it won't update the existing ones with their `curriculumSubType`, as those documents get updated only in the fields that weren't null (i.e. `tisid`, `label`), because the mapper ignores fields that are null in the record that's getting updated. So basically it would work for anything new but wouldn't update anything old, cos all the `"MEDICAL_CURRICULUM"` have no `curriculumSubtype`, while the new ones would be inserted correctly with `curriculumSubType` declared as `"SUB_SPECIALITY"`.

To allow for existing curricula (the `"MEDICAL_CURRICULUM"` ones) to be updated with the `curriculumSybType` value the CurriculumMapper needs to be changed with this line so that it will overwrite null fields instead of ignoring them: 
**@Mapping(target = "curriculumSubType"~~, ignore = true~~)**

2021-07-28 09:13 UTC, Judge40 requested changes

2021-07-28 09:13 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/trainee/reference/mapper/CurriculumMapper.java
> +  @Mapping(target = "curriculumSubType")
This line is not needed, mapping is automatic for matching fields.

2021-07-28 09:21 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/trainee/reference/mapper/CurriculumMapper.java
> +  @Mapping(target = "curriculumSubType")
This is the generated code without the manual mapping.

```java
@Override
public Curriculum update(Curriculum target, Curriculum source) {
    if ( source == null ) {
        return null;
    }
    target.setLabel( source.getLabel() );
    target.setCurriculumSubType( source.getCurriculumSubType() );
    return target;
}
```

2021-07-30 09:08 UTC, Judge40 approved these changes

2021-07-30 09:09 UTC, merged